### ISSUE TITLE
Find a recommended way of checking for fork/thread support

### ISSUE THREAD

**Issue by assertchris** [icicleio/concurrent#10]
<img width="1111" alt="screen shot 2015-11-09 at 11 32 44 am" src="https://cloud.githubusercontent.com/assets/200609/11023154/9f7934ce-86d5-11e5-9e66-ea2cab339724.png">

**Comment by sagebind** [comment]
How about https://github.com/icicleio/concurrent/commit/8f221501602b12690eead51c695b7af6c8c5dfc2? You can now use `Icicle\Forking\Fork::enabled()` and `Icicle\Threading\Thread::enabled()` to check for availability.

**Comment by sagebind** [comment]
This feature has now been released in [version 0.1.1](https://github.com/icicleio/concurrent/releases/tag/v0.1.1). Closing this issue.

**Comment by assertchris** [comment]
Hmmm, I thought I had replied to this already. It looks good, thanks.
